### ISSUE TITLE
Can this be used in Google Apps Script?

### ISSUE THREAD

**Issue by BobRupholdt** [prescottprue/tsheets-sdk#6]
And since I clearly don't know enough to know how, how might I go about that?

I can create matching files for each file herein but there's something happening there that's beyond my learning level.

**Comment by prescottprue** [comment]
I have never used Google Apps Script before, so it would take a bit of research to find out. This library was originally meant to be used with nodejs, but could potentially be modified to work.

**Comment by BobRupholdt** [comment]
I've never used node so I can't file the script well. Google script is a
rather vanilla JavaScript where most everything has to be in functions (or
classes.)

**Comment by nmccready** [comment]
@BRupholdt yes it can be. This PR is exactly why I forked this repo.

#7

**Comment by nmccready** [comment]
Granted this is a MAJOR change as Using request is set to be lazy loaded all the way up the chain.

**Comment by nmccready** [comment]
@BRupholdt you will need to shim in Promises and a lot of other things to make it work in Google App Script. But it is all possible and (relative) easy with webpack, e6-promise, and babel.

**Comment by nmccready** [comment]
This is pretty close to the actual webpack config I am using.

https://gist.github.com/nmccready/6243c6ed0257a8e4db39672b8e029392

Things to note:

I removed lodash and made my own poor man's version to keep the bundle size down. The
`'transform-es3-member-expression-literals',` `'transform-es3-property-literals'` transforms are vital for getting the JS bundle to work in GApp script as it only supports ES3 .

There are other oddities as setTimeout does not exist (google app script is synchronous). Therefore you need to shim it in again.

**Comment by nmccready** [comment]
Lastly use [clasp](https://github.com/google/clasp) to upload your bundle and src.

**Comment by prescottprue** [comment]
@nmccready Commented on the PR -- thanks for the awesome additions! Totally open to the changes, we just need to make sure it is documented well so the change doesn't confuse anyone who may install the new version.

**Comment by prescottprue** [comment]
[`v1.0.0` release](https://github.com/prescottprue/tsheets-sdk/releases/tag/v1.0.0) includes the changes made by @nmccready.
